name: Django CI

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    runs-on: ubuntu-latest
    strategy:
      matrix:
    

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ljkesmeer/demo-app
        tags: v1, latest
        registry: registry-url.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
